### ISSUE TITLE
AWAC - Import Warnings and plots

### ISSUE THREAD

**Issue by FelicityMc** [aodn/imos-toolbox#464] opened 2017-08-11 03:28 UTC
When importing AWAC data with waves (.wpr  and/or .wpb) a warning is issued:
Warning : F:\IMOS\Process\TS\QIMOS\Trip6514\Data\GBROTE-1603\Nortek\ote3401.wpb contains data sector type of varying size!
Cannot read this sector type : hex 62 == 98, with vectorised code.
Data does import but plots are erroneous - see attached file

**Comment by ggalibert** [comment] 2017-08-14 01:32
Will have a look but there is no attached file.

**Comment by ggalibert** [comment] 2017-08-14 07:08
Regarding the warning message:
> Warning : F:\IMOS\Process\TS\QIMOS\Trip6514\Data\GBROTE-1603\Nortek\ote3401.wpb contains data sector type of varying size!
> Cannot read this sector type : hex 62 == 98, with vectorised code.

This is due to the new vectorised (faster) parser for Nortek files. In some files, some sector types can have their size vary within a dataset and this is not supported in the new parser. The impacted sectors are the following:
* hex 60 (96): Wave Parameter Estimates
* hex 61 (97): Wave Band Estimates
* hex 62 (98): Wave Energy Spectrum
* hex 63 (99): Wave Fourier Coefficient Spectrum
* hex 65 (101): AST

I had discussed this with @sspagnol and this is currently no drama since the AWAC wave data is currently being read from the processed wave text files (.whd, .wap, .was, .wdr, .wds). For now this is just a warning we need to remain aware of.

**Comment by ggalibert** [comment] 2017-08-14 08:06
Which version of the toolbox are you using?
Which plots are erroneous: from the main window or from the exported diagnostic plots?

On Linux with v2.5.31 I get the following exported plots which look fine:
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_scatter_wcur_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263147-0061ab7c-811b-11e7-964b-e72ee721107a.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_scatter_vcur_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263148-0061d3d6-811b-11e7-9aa5-f16031bb6e2b.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_scatter_ucur_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263152-00631ce6-811b-11e7-88de-596ede325e51.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_scatter_temp_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263150-0062ba1c-811b-11e7-91b5-faf52e981679.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_scatter_cspd_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263151-0062d272-811b-11e7-83b1-72bc7afafe86.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_scatter_cdir_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263149-006242bc-811b-11e7-9f95-f8bd0af4b108.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_line_temp_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263153-0089d30e-811b-11e7-8e4f-71e26663c51b.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_line_pres_rel_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263155-009c5600-811b-11e7-902b-1dbb5fcfff09.png)
![imos_australian-institute-of-marine-science_gbrote_fv01_gbrote-1603_line_depth_c-20170814t075708z](https://user-images.githubusercontent.com/3498686/29263154-008b5792-811b-11e7-8561-d107f1d4f462.png)

**Comment by FelicityMc** [comment] 2017-08-14 22:19
I tried to attach the image but it would not work in GitHub. It is the plot in the diagnostic window.

**Comment by ggalibert** [comment] 2017-08-14 23:45
You can attach image files by dragging & dropping or by selecting them. See GitHub user interface screenshot below.
![screenshot from 2017-08-15 09-44-20](https://user-images.githubusercontent.com/3498686/29296551-5a25e65e-819e-11e7-9932-7e1d30d161c9.png)

**Comment by FelicityMc** [comment] 2017-08-14 23:46
I tried both of those and they didn’t work – is it browser dependent?

**Comment by ggalibert** [comment] 2017-08-14 23:50
I'm a bit puzzled. This works both on Firefox and Chromium. Pretty sure this is well supported across browsers. What is limiting is the file format though, not all file format are supported to be attached but .png is fine. Could you please try again and tell me which error message you're facing if any? Thanks.

![screenshot from 2017-08-15 09-44-20](https://user-images.githubusercontent.com/3498686/29296638-ec24101c-819e-11e7-8e1b-e568ecb08101.png)

**Comment by FelicityMc** [comment] 2017-08-15 00:48
Test Attach File
![2017-08-11 13_22_20-imos-toolbox v2 5 31 - pcwin64](https://user-images.githubusercontent.com/17605815/29297882-4b1c9474-81a7-11e7-9e16-1c61fbbe6bf7.png)

**Comment by ggalibert** [comment] 2017-08-15 00:56
Ok, thanks for that. I can see there is an issue with the plots on the main windows though where the X axis are not aligned between 2D and 1D plots. Will have a look at that on my windows VM. 
1. Could you please tell me whether you're running the toolbox in standalone or within Matlab? 
2. If within Matlab, which version are you using?

**Comment by ggalibert** [comment] 2017-09-13 00:00
@FelicityMc , could you please give me more information? See post above.

**Comment by ggalibert** [comment] 2017-09-13 01:19
Ok, I have been able to reproduce this. Will try to implement a fix.

**Comment by ggalibert** [comment] 2017-09-21 06:13
Fixed by https://github.com/aodn/imos-toolbox/commit/38fdcb91e1a95fc9119af4b061d8c94f02b32aad  in v2.5.33.

**Closed by ggalibert** 2017-09-21 06:13 UTC
