### ISSUE TITLE
Inferring Depth from only one neighbouring pressure sensor on mooring

### ISSUE THREAD

**Issue by TimAus-NSW** [aodn/imos-toolbox#478] opened 2017-10-11 03:28 UTC
![ch050_1706_all_depth](https://user-images.githubusercontent.com/17285217/31420884-ea1352f6-ae8f-11e7-9b3f-4b7df5d144c7.png)

Top of mooring broke free, taking the top Pressure/Temperature logger with it (and float, thus mooring lying on bottom after this point), subsequently only 1 PT left on the mooring (close to the bottom). The inferred depths for the Temperature loggers on the mooring increase in amplitude as they approach the surface reaching unrealistic values.

**Comment by ggalibert** [comment] 2017-10-11 04:14
This is caused by this recent change in v2.5.32: https://github.com/aodn/imos-toolbox/commit/efd7e973b76639a64014a41b3cc6cecac941c75a.

While this change does a bit better than before in the cause of a single PT above all others, it does a worse job in the case of a single PT below all others. So maybe will implement a combination of two solution depending on where the PT lies with regards to others.

**Comment by ggalibert** [comment] 2017-10-11 06:08
This is now fixed in v2.5.35 via commit https://github.com/aodn/imos-toolbox/commit/86366699bafd05de63861edffca0bf87ee78f3b5 .

**Closed by ggalibert** 2017-10-11 06:08 UTC
