### ISSUE TITLE
legend and date format to check for pressure drift

### ISSUE THREAD

**Issue by anaredd** [aodn/imos-toolbox#493] opened 2018-03-14 04:45 UTC
When using the tool: "check pressure differences between selected instrument and nearest neightbours' the plot produced by the toolbox doesn’t have the legend for the instruments plotted, so it is quite hard to QC the data. In addition the x-axis shows the date in numerical format (matlab datenumber).
[Note using windows 10 & matlab 2017a or matlab 2016b]

![qcpressuredrift](https://user-images.githubusercontent.com/17558169/37383713-54141b3a-279a-11e8-822e-67f73a04b381.PNG)

**Comment by ggalibert** [comment] 2018-03-14 05:50
Are you using v2.5.36 of the toolbox?

Is there any message error being output in the console?

I have tried with Windows 7 - 64bit and Matlab R2016b 64bit and unfortunately I couldn't reproduce this problem. I note that the legend and X axis label take 0.5 to 1sec to appear after the window first pops-up.

**Comment by anaredd** [comment] 2018-03-14 05:55
I forgot to add the error message. We are using v2.5.36 yes.
 
Matrix index is out of range for deletion.
Error in checkMooringPresDiffs (line 298)
        iOthersLogical(iNan) = [];
Error in mainWindow/displayCheckPressDiffs (line 557)
        checkMooringPresDiffs(sample_data, iSampleMenu, isQC, false, ''); 
Error while evaluating Menu Callback.

**Comment by ggalibert** [comment] 2018-03-15 01:33
Thanks, I've now managed to reproduce the error and also got a fix for it. This error happens when the selected instrument is the one that will be the nearest to the surface in the top plot.

However I now realise that the mapping between instruments and coloured lines in the legend doesn't make sense. Will try to fix this as well.

**Comment by ggalibert** [comment] 2018-03-22 06:28
Fixed in v2.5.37 vi commit https://github.com/aodn/imos-toolbox/commit/e94e8b5b83b85383cf9f59a25c96efc406e36d53.

**Closed by ggalibert** 2018-03-22 06:28 UTC
